### ISSUE TITLE
How to generate non-square images ?

### ISSUE THREAD

**Issue by O-O1024** [chail/anyres-gan#8]
I notice the example in #quickstart-with-pretrained-models can only generates square images.
I modify the code, let width and height be different, it will not work.
Of course, this question is not about panorama training.

Is it limited by the architecture of stylegan3 ?

**Comment by chail** [comment]
Yes you're correct that the model outputs square patches. For non-square images, perhaps you can try to arrange the patches to your desired aspect ratio? Overlapping patches are fine.

**Comment by O-O1024** [comment]
It seems cannot outpaint because it's chaotic outside range[-1,1].
![res-168555312014-8](https://github.com/chail/anyres-gan/assets/44624598/1528c635-de2c-4b20-be21-b30c4fb5e715)
![res-168555318943-9](https://github.com/chail/anyres-gan/assets/44624598/2a9555d0-0490-452a-91de-77a413afde6f)
![res-168555355405-1](https://github.com/chail/anyres-gan/assets/44624598/26c295ed-b340-4306-839b-2860c3daac40)
![res-168555376243-4](https://github.com/chail/anyres-gan/assets/44624598/c9ffaa7b-8dc3-4bb6-b916-559c1e4de684)

**Comment by chail** [comment]
I wouldn't expect that outpainting would work well since the model hasn't been trained on those coordinate ranges. You could set a non-square coordinate grid during training, as long as you are sampling square patches of it for training. For example, the panorama setup uses a 1:6 aspect ratio -- among other things, but the idea is that your coordinate grid for training doesn't have to be square as long as it makes sense for your dataset domain. 

At inference time, I would expect that you wouldn't be able to change the aspect ratio of your coordinate grid, unless you are doing a crop. 

I hope that helps!

**Comment by O-O1024** [comment]
Thank you  for your patient answer. I'll try it. @chail
